title: yashgoyal07
description: "Pythonista, Mechanical Engineer, Interested in computer science, Robotics & Business"
author:
  name: "yashgoyal07"
  email: "yashgoyalcs@gmail.com"
  url: "https://yashgoyal07.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "yashgoyal07"
year : "2021"
